apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-privileged-scc-netscale
  namespace: citrix
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: tailscale-router
    namespace: citrix
