apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: win10
  namespace: openshift-virtualization-os-images
spec:
  source:
    registry:
      url: "docker://quay.io/rh_ee_cschmitz/golden-image:win10"
  storage:
    storageClassName: gp3-csi
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 25Gi
