apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: win2k19
  namespace: openshift-virtualization-os-images
spec:
  source:
    registry:
      url: "docker://quay.io/rh_ee_cschmitz/golden-image:2k19"
  storage:
    storageClassName: gp3-csi-now
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi

