apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lightspeed-operator
  namespace: openshift-gitops
  labels:
    type: operator
spec:
  destination:
    name: in-cluster
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/operators/Lightspeed
    repoURL: https://github.com/joelapatatechaude/ocluster
  syncPolicy:
    automated: {}
    syncOptions:
      - Prune=true
      - CreateNamespace=true
