apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: add-label-to-zeadmin-devspaces-secret
  namespace: patch-operator
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    add-label:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        namespace: zeadmin-devspaces
        name: openai-api-keys
      patchTemplate: |
        metadata:
          labels:
            controller.devfile.io/mount-to-devworkspace: 'true'
            controller.devfile.io/watch-secret: 'true'
          annotations:
            controller.devfile.io/mount-as: env
      patchType: application/merge-patch+json
