apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: add-label-to-openshift-devspaces-namespace
  namespace: patch-operator
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    add-label:
      targetObjectRef:
        apiVersion: v1
        kind: Namespace
        name: zeadmin-devspaces
      patchTemplate: |
        metadata:
          labels:
            openai-token: yes-please
      patchType: application/merge-patch+json
