apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
spec:
  llm:
    providers:
      - credentialsSecretRef:
          name: openai-api-keys
        models:
          - name: gpt-4.1-mini
            parameters: {}
        name: myOpenai
        type: openai
        url: 'https://api.openai.com/v1'

  ols:
    defaultModel: gpt-4.1-mini
    defaultProvider: myOpenai
    logLevel: INFO
    introspectionEnabled: true
    userDataCollection:
      feedbackDisabled: false
      transcriptsDisabled: false
  olsDataCollector:
    logLevel: INFO
