apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: add-label-to-lightspeed-namespace
  namespace: patch-operator
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    add-label:
      targetObjectRef:
        apiVersion: v1
        kind: Namespace
        name: openshift-lightspeed
      patchTemplate: |
        metadata:
          labels:
            openai-token: yes-please
            granite-lightspeed-maas: yes-please
            qwen-14b-lightspeed-maas: yes-please
            mistral-24b-lightspeed-maas: yes-please
      patchType: application/merge-patch+json
