apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-cpu
  namespace: vllm-cpu
  labels:
    app: vllm-cpu
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: vllm-cpu
  template:
    metadata:
      labels:
        app: vllm-cpu
    spec:
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: vllm-cpu-config

      - name: cache-volume
        persistentVolumeClaim:
          claimName: vllm-cpu
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "10Gi"
      containers:
      - name: vllm-cpu
        image: public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:v0.10.2
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve ibm-granite/granite-4.0-micro --trust-remote-code --enable-chunked-prefill --max-model-len 8192"
        ]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-api-token
              key: hf-api-token
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "4"
            memory: 16G
          requests:
            cpu: "4"
            memory: 16G
        volumeMounts:
        - mountPath: /.config
          name: config-volume
        - mountPath: /.cache
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 300
          periodSeconds: 5
