apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-cpu
  namespace: vllm-cpu
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  volumeMode: Filesystem
