apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
  name: nvidia-gpu-operator-xyz
  namespace: nvidia-gpu-operator
spec:
  targetNamespaces:
  - nvidia-gpu-operator
  upgradeStrategy: Default
