apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-state-pvc
  namespace: tailscale-not-operator
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
